apiVersion: 1

datasources:
  - name: Prometheus
    uid: costlens-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 60s
